package com.shortlink.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.shortlink.entity.Url;
import com.shortlink.user.User;

// Spring Data JPA Repository for managing Url entities.
public interface UrlRepository extends JpaRepository<Url, Long> {

    // Finds a Url entity by its unique short code.
    Optional<Url> findByShortCode(String shortCode);

    // Checks if a Url entity exists with the given short code.
    boolean existsByShortCode(String shortCode);

    // Atomically increments the click count for a URL given its ID.
    @Modifying
    @Query("UPDATE Url u SET u.clickCount = u.clickCount + 1 WHERE u.id = :id")
    void incrementClickCount(@Param("id") Long id);

    // Finds all URLs created by a specific user.
    List<Url> findAllByUser(User user);

    // Finds paginated URLs created by a specific user.
    Page<Url> findAllByUser(User user, Pageable pageable);

    // Counts total URLs created by a user.
    long countByUser(User user);

    // Sums total clicks generated by a user's URLs.
    @Query("SELECT COALESCE(SUM(u.clickCount), 0) FROM Url u WHERE u.user = :user")
    long sumClicksByUser(@Param("user") User user);

    // Deletes all URLs belonging to a user.
    void deleteByUser(User user);

    // Counts URLs created after a specific timestamp.
    long countByCreatedAtAfter(java.time.LocalDateTime since);

    // Counts usable active URLs (no expiry or not yet expired).
    @Query("SELECT COUNT(u) FROM Url u WHERE u.expiresAt IS NULL OR u.expiresAt > :now")
    long countActiveUrls(@Param("now") java.time.LocalDateTime now);

    // Aggregates short URL creation daily for Admin Growth Chart.
    @Query("SELECT FUNCTION('to_char', u.createdAt, 'YYYY-MM-DD'), COUNT(u) FROM Url u WHERE u.createdAt >= :since GROUP BY FUNCTION('to_char', u.createdAt, 'YYYY-MM-DD') ORDER BY FUNCTION('to_char', u.createdAt, 'YYYY-MM-DD') ASC")
    List<Object[]> getNewUrlsTimeSeriesDaily(@Param("since") java.time.LocalDateTime since);

    // Finds most recently created URLs.
    List<Url> findTop10ByOrderByCreatedAtDesc();

    // Finds highest clicked URLs across the platform.
    List<Url> findTop10ByOrderByClickCountDesc();
}
